### ISSUE TITLE
Make fails with "nm.c:1699:28: error: 'sbrk' is deprecated"

### ISSUE THREAD

**Issue by ekinakoglu** [intel-gdb/vla#1]
The build of the master branch of vla fails during the make process. Below are the commands I issued:

$ ./configure --prefix=/opt/intel-gdb/
...
$ make
...
gcc -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl -DLOCALEDIR="\"/opt/intel-gdb/share/locale\"" -Dbin_dummy_emulation=bin_vanilla_emulation  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -g -O2 -MT nm.o -MD -MP -MF .deps/nm.Tpo -c -o nm.o nm.c
nm.c:1699:28: error: 'sbrk' is deprecated [-Werror,-Wdeprecated-declarations]
      char _lim = (char *) sbrk (0);
                           ^
/usr/include/unistd.h:582:7: note: 'sbrk' declared here
void    *sbrk(int);
         ^
1 error generated.
make[4]: *_\* [nm.o] Error 1
make[3]: **\* [all-recursive] Error 1
make[2]: **\* [all] Error 2
make[1]: **\* [all-binutils] Error 2
make: **\* [all] Error 2

Could you please share your view on what could be wrong? Thanks.

Ekin

**Comment by ekinakoglu** [comment]
Further, changing "gdb" folder in "vla" root directory and issuing "./configure" and then "make" fails with message below:

gcc -g -O2   -I. -I. -I./common -I./config -DLOCALEDIR="\"/opt/intel-gdb/share/locale\"" -DHAVE_CONFIG_H -I./../include/opcode -I./../opcodes/.. -I./../readline/.. -I../bfd -I./../bfd -I./../include -I../libdecnumber -I./../libdecnumber -I./../intl -I./gnulib/import -Ibuild-gnulib/import   -DTUI=1  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Wall -Wdeclaration-after-statement -Wpointer-arith -Wpointer-sign -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wmissing-prototypes -Wdeclaration-after-statement -Wempty-body -Wmissing-parameter-type -Wold-style-declaration -Wold-style-definition -Wformat-nonliteral -Werror -c -o gdb.o -MT gdb.o -MMD -MP -MF .deps/gdb.Tpo gdb.c
error: unknown warning option '-Wmissing-parameter-type' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wold-style-declaration'; did you mean '-Wout-of-line-declaration'? [-Werror,-Wunknown-warning-option]
make: **\* [gdb.o] Error 1

**Comment by ghost** [comment]
Hello Ekin,

it looks like you tried to configure/build gdb from the toplevel tree. Please try the following steps:

$ mkdir build
$ cd build
$ ../vla-clone/gdb/configure –prefix=/opt/intel-gdb

This should build gdb out of tree, where “vla-clone” is your cloned repository.

-Sanimir

**Comment by ekinakoglu** [comment]
My machine is OS X Mavericks (10.9.4) on Mac Mini and gcc (actually clang) version is:

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix

**Comment by ghost** [comment]
Hello Ekin,

thanks for trying out vla on OS X, we have not so far =D

Can you try adding --disable-werror to skip the not supported options? Other than that it seems to be a generic issue, could you successfully build vanilla gdb on Mavericks?

-Sanimir

**Comment by ekinakoglu** [comment]
Dear Sanimir,

Thank you very much for your useful suggestions. With a separate build directory, it worked but "make" complained about "error: unknown warning option" because my compiler is actually LLVM/Clang but not GCC. Hence, I switched to gcc with:

$ CC=gcc-mp-4.8 /Users/ekinakoglu/vla/gdb/configure --prefix=/opt/intel-gdb/

and "make" worked without those complaints. However, this time "make" failed with another error complaining about no "version.c" file exists as below:

gcc-mp-4.8 -g -O2   -I. -I/Users/ekinakoglu/vla/gdb -I/Users/ekinakoglu/vla/gdb/common -I/Users/ekinakoglu/vla/gdb/config -DLOCALEDIR="\"/opt/intel-gdb/share/locale\"" -DHAVE_CONFIG_H -I/Users/ekinakoglu/vla/gdb/../include/opcode -I/Users/ekinakoglu/vla/gdb/../opcodes/.. -I/Users/ekinakoglu/vla/gdb/../readline/.. -I../bfd -I/Users/ekinakoglu/vla/gdb/../bfd -I/Users/ekinakoglu/vla/gdb/../include -I../libdecnumber -I/Users/ekinakoglu/vla/gdb/../libdecnumber  -I/Users/ekinakoglu/vla/gdb/gnulib/import -Ibuild-gnulib/import   -DTUI=1  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Wall -Wdeclaration-after-statement -Wpointer-arith -Wpointer-sign -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wmissing-prototypes -Wdeclaration-after-statement -Wempty-body -Wmissing-parameter-type -Wold-style-declaration -Wold-style-definition -Wformat-nonliteral -Werror -c -o version.o -MT version.o -MMD -MP -MF .deps/version.Tpo version.c
gcc-mp-4.8: error: version.c: No such file or directory
gcc-mp-4.8: fatal error: no input files
compilation terminated.
make: **\* [version.o] Error 1

Do you have an idea on this? Thanks.

Ekin

**Comment by ghost** [comment]
Hello Ekin,

I will try to reproduce your issue on Mavericks but first I need to setup an environment similar to yours. So don’t hold your breath =D

-Sanimir

**Comment by ekinakoglu** [comment]
Thank you. I will be looking forward to hearing updates from you.

**Comment by ekinakoglu** [comment]
One last update: Indeed, there is no file named "version.c" in gdb folder. But there is a file called "version.in". Though, I do not know if the two files are somehow related.

**Comment by kboell** [comment]
Try to do the following:
cd <gdb-src-dir>
mkdir build
cd build
../configure --disable-werror
make

This worked for me with gcc and clang on MacOS Mavericks.
- Keven

**Comment by ekinakoglu** [comment]
Dear Keven,

I tried your suggestion but it seems like it does no effect on the compile options. GCC failed with the same error (complaining about no "version.c" found) and Clang failed with a similar error like below:

gcc -g -O2   -I. -I/Users/ekinakoglu/vla/gdb -I/Users/ekinakoglu/vla/gdb/common -I/Users/ekinakoglu/vla/gdb/config -DLOCALEDIR="\"/opt/intel-gdb/share/locale\"" -DHAVE_CONFIG_H -I/Users/ekinakoglu/vla/gdb/../include/opcode -I/Users/ekinakoglu/vla/gdb/../opcodes/.. -I/Users/ekinakoglu/vla/gdb/../readline/.. -I../bfd -I/Users/ekinakoglu/vla/gdb/../bfd -I/Users/ekinakoglu/vla/gdb/../include -I../libdecnumber -I/Users/ekinakoglu/vla/gdb/../libdecnumber  -I/Users/ekinakoglu/vla/gdb/gnulib/import -Ibuild-gnulib/import   -DTUI=1  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Wall -Wdeclaration-after-statement -Wpointer-arith -Wpointer-sign -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wmissing-prototypes -Wdeclaration-after-statement -Wempty-body -Wmissing-parameter-type -Wold-style-declaration -Wold-style-definition -Wformat-nonliteral  -c -o gdb.o -MT gdb.o -MMD -MP -MF .deps/gdb.Tpo /Users/ekinakoglu/vla/gdb/gdb.c
warning: unknown warning option '-Wmissing-parameter-type' [-Wunknown-warning-option]
warning: unknown warning option '-Wold-style-declaration'; did you mean '-Wout-of-line-declaration'? [-Wunknown-warning-option]
In file included from /Users/ekinakoglu/vla/gdb/gdb.c:19:
In file included from /Users/ekinakoglu/vla/gdb/defs.h:65:
/Users/ekinakoglu/vla/gdb/common/gdb_locale.h:27:11: fatal error: 'libintl.h' file not found

Do you have any idea?

Thank you,

Ekin

**Comment by kboell** [comment]
It looks like you configured only the gdb directory.
Please execute the commands exactly like this (also clean your working sandbox, to not have any left overs from the previous builds):

cd <gdb-source-tree-root>
mkdir build
 cd build
 ../configure --disable-werror    # Please do not execute ../gdb/configure
 make

Keven

**Comment by kboell** [comment]
The Github page is filtering away some of my commands:

cd your-gdb-source-tree-root
mkdir build
cd build
../configure --disable-werror # Please do not execute ../gdb/configure
make

**Comment by ekinakoglu** [comment]
Thank you, Keven. It was built and installed without problems following what you instructed.

Ekin
