### ISSUE TITLE
GDB build from "intel-gdb/vla" from "vla-fortran" branch still cannot access variable length arrays in Fortran

### ISSUE THREAD

**Issue by ekinakoglu** [intel-gdb/vla#2]
The issue of not being able to access variable length arrays (VLA) during debugging as it is the case in vanilla GDB (https://sourceware.org/bugzilla/show_bug.cgi?id=9395) still exists in this projects' modified GDB. When asked to print the value of a VLA variable, GDB prints:

(gdb) Cannot perform substring on this type

Is this issue still not resolved in this project?

Thanks.

Ekin

**Comment by kboell** [comment]
The support for VLA's in C99 is already upstream, so a vanilla GDB ([gdb](http://www.gnu.org/software/gdb/)) will work.
If you are interested in Fortran VLA support, please checkout vla-fortran from this repository.

This repository is _not_ a clone of the official GDB repository and the master branch is not up to date.

Keven

**Comment by ekinakoglu** [comment]
Thank you very much, Keven.

**Comment by ekinakoglu** [comment]
Dear Keven,

I cloned "vla-fortran" branch, and build and installed GDB. However, the program gives the same error when trying to reach VLAs in a debugging session as:

(gdb) Cannot perform substring on this type

May I assume that VLA feature has not been implemented yet for debugging Fortran programs?

Thank you.

Ekin

**Comment by kboell** [comment]
It is implemented for Fortran, otherwise I would not mention it ;-)
I'm not sure what you are trying to do when you are saying that you want to reach a VLA.

Example:

```
REAL, ALLOCATABLE :: vla (:, :)
ALLOCATE (vla (2,2))
vla (: , :) = 1

(gdb) p vla
$1 = (( 1, 1) ( 1, 1) )
```

Please try out one of the example programs in the test suite gdb/testsuite/gdb.fortran/vla*.f90
They are known to work.

Keven

**Comment by ekinakoglu** [comment]
I think something is wrong with my build/installation from "vla-fortran" branch because example "vla-datatypes.f90" does not work. I will investigate this.

Thank you very much.

Ekin

**Comment by ekinakoglu** [comment]
Is this the correct way to clone the vla-fortran branch?

$ git clone -b vla-fortran https://github.com/intel-gdb/vla.git

I did like that and built and installed as you've instructed before. But still I cannot access VLAs.

Thank you.

Ekin

**Comment by ekinakoglu** [comment]
To no avail... OK, I wiped out everything and cloned a fresh "vla-fortran" again with:

$ git clone -b vla-fortran --single-branch https://github.com/intel-gdb/vla.git

and built and installed like:

$ mkdir build
$ cd build
$ ../configure --disable-werror --prefix=/opt/intel-gdb
$ make
$ sudo make install

Then tried "vla-datatypes.f90" in "~/vla/gdb/testsuite/gdb.fortran" as an example like:

$ gfortran -g vla-datatypes.f90
$ /opt/intel-gdb/bin/gdb a.out
GNU gdb (GDB) 7.8.50.20140722-cvs
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin13.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...Reading symbols from /Users/ekinakoglu/Documents/vla/gdb/testsuite/gdb.fortran/a.out.dSYM/Contents/Resources/DWARF/a.out...done.
done.
(gdb) break main
Breakpoint 1 at 0x100001ce0: file vla-datatypes.f90, line 51.
(gdb) run
Starting program: /Users/ekinakoglu/Documents/vla/gdb/testsuite/gdb.fortran/a.out 
Breakpoint 1, main (argc=1, argv=0x7fff5fbffbf8) at vla-datatypes.f90:51
51  end program vla_primitives
(gdb) step 11
(gdb) p intvla(1,1,1)
Cannot perform substring on this type

Still VLAs are inaccessible. Do you have any idea?

Thank you.

Ekin

**Comment by ekinakoglu** [comment]
I have just tried again following Kevin's latest commits dated back to January and now confirm that the issue is fixed. Thank you very much, Kevin.
